// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
)

type AuthProvider struct {
	mock.Mock
}

func (_m *AuthProvider) Login(ctx context.Context) error {
	ret := _m.Called(ctx)
	return ret.Error(0)
}

func (_m *AuthProvider) Token(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)
	return ret.String(0), ret.Error(1)
}

func (_m *AuthProvider) Logout(ctx context.Context) error {
	ret := _m.Called(ctx)
	return ret.Error(0)
}

func NewAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthProvider {
	mock := &AuthProvider{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
