// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	"context"

	"github.com/cdimonaco/tokenpile/internal/provider"
	"github.com/cdimonaco/tokenpile/internal/usage"
	"github.com/stretchr/testify/mock"
)

type IssueProvider struct {
	mock.Mock
}

func (_m *IssueProvider) ListIssues(ctx context.Context, filter usage.Filter) ([]provider.Issue, error) {
	ret := _m.Called(ctx, filter)

	var r0 []provider.Issue
	if rf, ok := ret.Get(0).(func(context.Context, usage.Filter) []provider.Issue); ok {
		r0 = rf(ctx, filter)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]provider.Issue)
	}

	return r0, ret.Error(1)
}

func (_m *IssueProvider) GetIssue(ctx context.Context, repo string, number int) (*provider.Issue, error) {
	ret := _m.Called(ctx, repo, number)

	var r0 *provider.Issue
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *provider.Issue); ok {
		r0 = rf(ctx, repo, number)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*provider.Issue)
	}

	return r0, ret.Error(1)
}

func NewIssueProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssueProvider {
	mock := &IssueProvider{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
