// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	"context"

	"github.com/cdimonaco/tokenpile/internal/domain"
	"github.com/stretchr/testify/mock"
)

type IssueProvider struct {
	mock.Mock
}

func (_m *IssueProvider) ListIssues(ctx context.Context, filter domain.IssueFilter) ([]domain.Issue, error) {
	ret := _m.Called(ctx, filter)

	var r0 []domain.Issue
	if rf, ok := ret.Get(0).(func(context.Context, domain.IssueFilter) []domain.Issue); ok {
		r0 = rf(ctx, filter)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.Issue)
	}

	return r0, ret.Error(1)
}

func (_m *IssueProvider) GetIssue(ctx context.Context, repo string, number int) (*domain.Issue, error) {
	ret := _m.Called(ctx, repo, number)

	var r0 *domain.Issue
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *domain.Issue); ok {
		r0 = rf(ctx, repo, number)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Issue)
	}

	return r0, ret.Error(1)
}

func NewIssueProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssueProvider {
	mock := &IssueProvider{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
