// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	provider "github.com/cdimonaco/tokenpile/internal/provider"
	mock "github.com/stretchr/testify/mock"

	usage "github.com/cdimonaco/tokenpile/internal/usage"
)

// IssueProvider is an autogenerated mock type for the IssueProvider type
type IssueProvider struct {
	mock.Mock
}

// GetIssue provides a mock function with given fields: ctx, repo, number
func (_m *IssueProvider) GetIssue(ctx context.Context, repo string, number int) (*provider.Issue, error) {
	ret := _m.Called(ctx, repo, number)

	if len(ret) == 0 {
		panic("no return value specified for GetIssue")
	}

	var r0 *provider.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*provider.Issue, error)); ok {
		return rf(ctx, repo, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *provider.Issue); ok {
		r0 = rf(ctx, repo, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, repo, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListIssues provides a mock function with given fields: ctx, filter
func (_m *IssueProvider) ListIssues(ctx context.Context, filter usage.Filter) ([]provider.Issue, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListIssues")
	}

	var r0 []provider.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usage.Filter) ([]provider.Issue, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usage.Filter) []provider.Issue); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]provider.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usage.Filter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIssueProvider creates a new instance of IssueProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssueProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssueProvider {
	mock := &IssueProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
