// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	"context"

	"github.com/cdimonaco/tokenpile/internal/domain"
	"github.com/stretchr/testify/mock"
)

type Store struct {
	mock.Mock
}

func (_m *Store) LogUsage(ctx context.Context, entry domain.UsageEntry) error {
	ret := _m.Called(ctx, entry)
	return ret.Error(0)
}

func (_m *Store) ListIssues(ctx context.Context, filter domain.IssueFilter) ([]domain.TrackedIssue, error) {
	ret := _m.Called(ctx, filter)

	var r0 []domain.TrackedIssue
	if rf, ok := ret.Get(0).(func(context.Context, domain.IssueFilter) []domain.TrackedIssue); ok {
		r0 = rf(ctx, filter)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.TrackedIssue)
	}

	return r0, ret.Error(1)
}

func (_m *Store) GetReport(ctx context.Context, repo string, issueNum int) (*domain.Report, error) {
	ret := _m.Called(ctx, repo, issueNum)

	var r0 *domain.Report
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *domain.Report); ok {
		r0 = rf(ctx, repo, issueNum)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Report)
	}

	return r0, ret.Error(1)
}

func (_m *Store) StartSession(ctx context.Context, repo string, issueNum int) (*domain.Session, error) {
	ret := _m.Called(ctx, repo, issueNum)

	var r0 *domain.Session
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *domain.Session); ok {
		r0 = rf(ctx, repo, issueNum)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Session)
	}

	return r0, ret.Error(1)
}

func (_m *Store) EndSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)
	return ret.Error(0)
}

func (_m *Store) ListSessions(ctx context.Context, repo string, issueNum int) ([]domain.Session, error) {
	ret := _m.Called(ctx, repo, issueNum)

	var r0 []domain.Session
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.Session); ok {
		r0 = rf(ctx, repo, issueNum)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.Session)
	}

	return r0, ret.Error(1)
}

func (_m *Store) ListUsageOverTime(ctx context.Context, filter domain.UsageOverTimeFilter) ([]domain.UsagePoint, error) {
	ret := _m.Called(ctx, filter)

	var r0 []domain.UsagePoint
	if rf, ok := ret.Get(0).(func(context.Context, domain.UsageOverTimeFilter) []domain.UsagePoint); ok {
		r0 = rf(ctx, filter)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.UsagePoint)
	}

	return r0, ret.Error(1)
}

func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
