// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	"context"
	"time"

	"github.com/cdimonaco/tokenpile/internal/usage"
	"github.com/stretchr/testify/mock"
)

type Store struct {
	mock.Mock
}

func (_m *Store) LogUsage(ctx context.Context, entry usage.Entry) error {
	ret := _m.Called(ctx, entry)
	return ret.Error(0)
}

func (_m *Store) UpsertIssueCache(ctx context.Context, cache *usage.IssueCache) error {
	ret := _m.Called(ctx, cache)
	return ret.Error(0)
}

func (_m *Store) GetIssueCache(ctx context.Context, repo string, issueNum int) (*usage.IssueCache, error) {
	ret := _m.Called(ctx, repo, issueNum)

	var r0 *usage.IssueCache
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *usage.IssueCache); ok {
		r0 = rf(ctx, repo, issueNum)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*usage.IssueCache)
	}

	return r0, ret.Error(1)
}

func (_m *Store) ListEntries(ctx context.Context, filter usage.Filter) ([]usage.Entry, error) {
	ret := _m.Called(ctx, filter)

	var r0 []usage.Entry
	if rf, ok := ret.Get(0).(func(context.Context, usage.Filter) []usage.Entry); ok {
		r0 = rf(ctx, filter)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]usage.Entry)
	}

	return r0, ret.Error(1)
}

func (_m *Store) ListIssues(ctx context.Context, filter usage.Filter) ([]usage.TrackedIssue, error) {
	ret := _m.Called(ctx, filter)

	var r0 []usage.TrackedIssue
	if rf, ok := ret.Get(0).(func(context.Context, usage.Filter) []usage.TrackedIssue); ok {
		r0 = rf(ctx, filter)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]usage.TrackedIssue)
	}

	return r0, ret.Error(1)
}

func (_m *Store) GetReport(ctx context.Context, repo string, issueNum int) (*usage.Report, error) {
	ret := _m.Called(ctx, repo, issueNum)

	var r0 *usage.Report
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *usage.Report); ok {
		r0 = rf(ctx, repo, issueNum)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*usage.Report)
	}

	return r0, ret.Error(1)
}

func (_m *Store) StartSession(ctx context.Context, repo string, issueNum int) (*usage.Session, error) {
	ret := _m.Called(ctx, repo, issueNum)

	var r0 *usage.Session
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *usage.Session); ok {
		r0 = rf(ctx, repo, issueNum)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*usage.Session)
	}

	return r0, ret.Error(1)
}

func (_m *Store) EndSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)
	return ret.Error(0)
}

func (_m *Store) ListSessions(ctx context.Context, repo string, issueNum int) ([]usage.Session, error) {
	ret := _m.Called(ctx, repo, issueNum)

	var r0 []usage.Session
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []usage.Session); ok {
		r0 = rf(ctx, repo, issueNum)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]usage.Session)
	}

	return r0, ret.Error(1)
}

func (_m *Store) UpdateSessionAnnotations(ctx context.Context, sessionID string, note *string, tags []string) error {
	ret := _m.Called(ctx, sessionID, note, tags)
	return ret.Error(0)
}

func (_m *Store) ListUsageOverTime(ctx context.Context, filter usage.OverTimeFilter) ([]usage.Point, error) {
	ret := _m.Called(ctx, filter)

	var r0 []usage.Point
	if rf, ok := ret.Get(0).(func(context.Context, usage.OverTimeFilter) []usage.Point); ok {
		r0 = rf(ctx, filter)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]usage.Point)
	}

	return r0, ret.Error(1)
}

func (_m *Store) ListTrackedIssueRefs(ctx context.Context) ([]usage.TrackedIssueRef, error) {
	ret := _m.Called(ctx)

	var r0 []usage.TrackedIssueRef
	if rf, ok := ret.Get(0).(func(context.Context) []usage.TrackedIssueRef); ok {
		r0 = rf(ctx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]usage.TrackedIssueRef)
	}

	return r0, ret.Error(1)
}

func (_m *Store) EndSessionAt(ctx context.Context, sessionID string, at time.Time) error {
	ret := _m.Called(ctx, sessionID, at)
	return ret.Error(0)
}

func (_m *Store) UpdateSessionActivity(ctx context.Context, sessionID string, at time.Time) error {
	ret := _m.Called(ctx, sessionID, at)
	return ret.Error(0)
}

func (_m *Store) SetBudget(ctx context.Context, repo string, issueNum int, budget float64) error {
	ret := _m.Called(ctx, repo, issueNum, budget)
	return ret.Error(0)
}

func (_m *Store) UnsetBudget(ctx context.Context, repo string, issueNum int) error {
	ret := _m.Called(ctx, repo, issueNum)
	return ret.Error(0)
}

func (_m *Store) GetBudget(ctx context.Context, repo string, issueNum int) (*float64, error) {
	ret := _m.Called(ctx, repo, issueNum)

	var r0 *float64
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *float64); ok {
		r0 = rf(ctx, repo, issueNum)
	} else if ret.Get(0) != nil {
		v := ret.Get(0).(float64)
		r0 = &v
	}

	return r0, ret.Error(1)
}

func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
