// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	usage "github.com/cdimonaco/tokenpile/internal/usage"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// EndSession provides a mock function with given fields: ctx, sessionID
func (_m *Store) EndSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EndSessionAt provides a mock function with given fields: ctx, sessionID, at
func (_m *Store) EndSessionAt(ctx context.Context, sessionID string, at time.Time) error {
	ret := _m.Called(ctx, sessionID, at)

	if len(ret) == 0 {
		panic("no return value specified for EndSessionAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, sessionID, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBudget provides a mock function with given fields: ctx, repo, issueNum
func (_m *Store) GetBudget(ctx context.Context, repo string, issueNum int) (*float64, error) {
	ret := _m.Called(ctx, repo, issueNum)

	if len(ret) == 0 {
		panic("no return value specified for GetBudget")
	}

	var r0 *float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*float64, error)); ok {
		return rf(ctx, repo, issueNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *float64); ok {
		r0 = rf(ctx, repo, issueNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, repo, issueNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIssueCache provides a mock function with given fields: ctx, repo, issueNum
func (_m *Store) GetIssueCache(ctx context.Context, repo string, issueNum int) (*usage.IssueCache, error) {
	ret := _m.Called(ctx, repo, issueNum)

	if len(ret) == 0 {
		panic("no return value specified for GetIssueCache")
	}

	var r0 *usage.IssueCache
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*usage.IssueCache, error)); ok {
		return rf(ctx, repo, issueNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *usage.IssueCache); ok {
		r0 = rf(ctx, repo, issueNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usage.IssueCache)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, repo, issueNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReport provides a mock function with given fields: ctx, repo, issueNum
func (_m *Store) GetReport(ctx context.Context, repo string, issueNum int) (*usage.Report, error) {
	ret := _m.Called(ctx, repo, issueNum)

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 *usage.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*usage.Report, error)); ok {
		return rf(ctx, repo, issueNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *usage.Report); ok {
		r0 = rf(ctx, repo, issueNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usage.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, repo, issueNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllSessions provides a mock function with given fields: ctx
func (_m *Store) ListAllSessions(ctx context.Context) ([]usage.Session, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllSessions")
	}

	var r0 []usage.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]usage.Session, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []usage.Session); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usage.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBudgets provides a mock function with given fields: ctx
func (_m *Store) ListBudgets(ctx context.Context) ([]usage.IssueBudget, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBudgets")
	}

	var r0 []usage.IssueBudget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]usage.IssueBudget, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []usage.IssueBudget); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usage.IssueBudget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEntries provides a mock function with given fields: ctx, filter
func (_m *Store) ListEntries(ctx context.Context, filter usage.Filter) ([]usage.Entry, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListEntries")
	}

	var r0 []usage.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usage.Filter) ([]usage.Entry, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usage.Filter) []usage.Entry); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usage.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usage.Filter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListIssues provides a mock function with given fields: ctx, filter
func (_m *Store) ListIssues(ctx context.Context, filter usage.Filter) ([]usage.TrackedIssue, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListIssues")
	}

	var r0 []usage.TrackedIssue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usage.Filter) ([]usage.TrackedIssue, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usage.Filter) []usage.TrackedIssue); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usage.TrackedIssue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usage.Filter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSessions provides a mock function with given fields: ctx, repo, issueNum
func (_m *Store) ListSessions(ctx context.Context, repo string, issueNum int) ([]usage.Session, error) {
	ret := _m.Called(ctx, repo, issueNum)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []usage.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]usage.Session, error)); ok {
		return rf(ctx, repo, issueNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []usage.Session); ok {
		r0 = rf(ctx, repo, issueNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usage.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, repo, issueNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTrackedIssueRefs provides a mock function with given fields: ctx
func (_m *Store) ListTrackedIssueRefs(ctx context.Context) ([]usage.TrackedIssueRef, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTrackedIssueRefs")
	}

	var r0 []usage.TrackedIssueRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]usage.TrackedIssueRef, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []usage.TrackedIssueRef); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usage.TrackedIssueRef)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsageOverTime provides a mock function with given fields: ctx, filter
func (_m *Store) ListUsageOverTime(ctx context.Context, filter usage.OverTimeFilter) ([]usage.Point, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListUsageOverTime")
	}

	var r0 []usage.Point
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usage.OverTimeFilter) ([]usage.Point, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usage.OverTimeFilter) []usage.Point); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usage.Point)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usage.OverTimeFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogUsage provides a mock function with given fields: ctx, entry
func (_m *Store) LogUsage(ctx context.Context, entry usage.Entry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for LogUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usage.Entry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetBudget provides a mock function with given fields: ctx, repo, issueNum, budget
func (_m *Store) SetBudget(ctx context.Context, repo string, issueNum int, budget float64) error {
	ret := _m.Called(ctx, repo, issueNum, budget)

	if len(ret) == 0 {
		panic("no return value specified for SetBudget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, float64) error); ok {
		r0 = rf(ctx, repo, issueNum, budget)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartSession provides a mock function with given fields: ctx, repo, issueNum
func (_m *Store) StartSession(ctx context.Context, repo string, issueNum int) (*usage.Session, error) {
	ret := _m.Called(ctx, repo, issueNum)

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 *usage.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*usage.Session, error)); ok {
		return rf(ctx, repo, issueNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *usage.Session); ok {
		r0 = rf(ctx, repo, issueNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usage.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, repo, issueNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnsetBudget provides a mock function with given fields: ctx, repo, issueNum
func (_m *Store) UnsetBudget(ctx context.Context, repo string, issueNum int) error {
	ret := _m.Called(ctx, repo, issueNum)

	if len(ret) == 0 {
		panic("no return value specified for UnsetBudget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, repo, issueNum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSessionActivity provides a mock function with given fields: ctx, sessionID, at
func (_m *Store) UpdateSessionActivity(ctx context.Context, sessionID string, at time.Time) error {
	ret := _m.Called(ctx, sessionID, at)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, sessionID, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSessionAnnotations provides a mock function with given fields: ctx, sessionID, note, tags
func (_m *Store) UpdateSessionAnnotations(ctx context.Context, sessionID string, note *string, tags []string) error {
	ret := _m.Called(ctx, sessionID, note, tags)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionAnnotations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, []string) error); ok {
		r0 = rf(ctx, sessionID, note, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertIssueCache provides a mock function with given fields: ctx, cache
func (_m *Store) UpsertIssueCache(ctx context.Context, cache *usage.IssueCache) error {
	ret := _m.Called(ctx, cache)

	if len(ret) == 0 {
		panic("no return value specified for UpsertIssueCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *usage.IssueCache) error); ok {
		r0 = rf(ctx, cache)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
