version: 2

project_name: tokenpile

before:
  hooks:
    - go mod tidy

builds:
  - id: tokenpile
    main: ./cmd/tokenpile
    binary: tokenpile
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
        -X main.version={{.Version}}
        -X main.githubClientID={{ .Env.TOKENPILE_GITHUB_CLIENT_ID }}
        -X main.githubClientSecret={{ .Env.TOKENPILE_GITHUB_CLIENT_SECRET }}

archives:
  - id: tokenpile
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

release:
  github:
    owner: cdimonaco
    name: tokenpile

